window.PROJECTS = [
  {
    id: 'advent-of-kube',
    title: 'Advent of Kube',
    tags: ['Kubernetes', 'GitHub API', 'AI'],
    problem: '25 daily Kubernetes debugging challenges with no platform to deploy, track, and score them consistently.',
    aiUsage: 'Claude generated challenge scaffolding, wrote broken manifests to debug, and designed the grading rubric from natural language specs.',
    outcome: 'Full platform launching December 2026 with 10 challenges live.',
    github: 'https://github.com/MuhammedHMahmood/adventofkube',
  },
  {
    id: 'duo-class-notes',
    title: 'Duo Class Notes',
    tags: ['Whisper', 'Claude API', 'RAG'],
    problem: 'Students left dense lectures with incomplete notes and no reliable way to catch up before the next session.',
    aiUsage: 'Whisper transcribed lecture audio; Claude summarized key concepts and generated Q&A pairs; RAG let students query their own notes.',
    outcome: 'Deployed for CMPE281 pilot — students reported 30% less post-lecture confusion in informal feedback.',
    live: 'https://muhammedhmahmood.github.io/duo-alim-course-notes/',
  },
  {
    id: 'masjidi-revamp',
    title: 'Masjidi Revamp',
    tags: ['React Native', 'Firebase', 'Claude API'],
    problem: 'Existing mosque management app had poor UX for prayer time notifications and event announcements.',
    aiUsage: 'Claude proposed UX improvements from user complaint logs and generated Firebase notification pipeline boilerplate.',
    outcome: 'Shipped to 3 pilot mosques, reducing support tickets by 40%.',
    live: 'https://masjidiapp.com/',
  },
  {
    id: 'marks-revamp',
    title: 'Marks Revamp',
    tags: ['React Native', 'Expo', 'Firebase'],
    problem: 'Goal-tracking app had slow startup and clunky habit-streak UI that hurt daily engagement.',
    aiUsage: 'Claude reviewed component trees for re-render issues and proposed a state architecture that halved the bundle size.',
    outcome: 'Cold-start time down 60%; animated progress rings shipped; daily active use up 2×.',
    github: 'https://github.com/MuhammedHMahmood/marks',
    live: 'https://play.google.com/store/apps/details?id=com.lattice008.marks&hl=en_US',
  },
  {
    id: 'cloudkraft',
    title: 'CloudKraft',
    tags: ['Terraform', 'IaC', 'Leadership'],
    problem: 'Engineering teams had no way to keep architecture diagrams in sync with Terraform — documentation drifted as IaC evolved.',
    aiLabel: 'My Role',
    aiUsage: 'Project advisor. Guided a student team through IAM design, Terraform module structure, CI/CD pipeline optimization, and the full infrastructure management lifecycle.',
    outcome: 'Students shipped a working prototype that parses Terraform and renders live architecture diagrams, with reverse generation from diagram edits.',
  },
  {
    id: 'datatrust',
    title: 'DataTrust',
    tags: ['RAG', 'IAM', 'Leadership'],
    problem: 'Students set out to build a Claude-like assistant where data access is governed by IAM — integrating GitHub and Confluence as knowledge sources.',
    aiLabel: 'My Role',
    aiUsage: 'Project advisor. Guided the team through RAG architecture, chunking strategies, IAM-controlled data pipelines, and token budget management for large document sets.',
    outcome: 'Delivered a working prototype with role-based data access, GitHub and Confluence integrations, and a retrieval pipeline tuned to stay within token limits.',
  },
];
