window.PROJECTS = [
  {
    id: 'advent-of-kube',
    title: 'Advent of Kube',
    tags: ['Kubernetes', 'GitHub API', 'AI'],
    problem: '25 daily Kubernetes debugging challenges with no platform to deploy, track, and score them consistently.',
    aiUsage: 'Claude generated challenge scaffolding, wrote broken manifests to debug, and designed the grading rubric from natural language specs.',
    outcome: 'Full platform launching December 2026 with 10 challenges live.',
    github: 'https://github.com/MuhammedHMahmood/adventofkube',
  },
  {
    id: 'duo-class-notes',
    title: 'Duo Class Notes',
    tags: ['Whisper', 'Claude API', 'RAG'],
    problem: 'Students left dense AWS lectures with incomplete notes and no reliable way to catch up before the next lab.',
    aiUsage: 'Whisper transcribed lecture audio; Claude summarized key concepts and generated Q&A pairs; RAG let students query their own notes.',
    outcome: 'Deployed for CMPE281 pilot — students reported 30% less post-lecture confusion in informal feedback.',
  },
  {
    id: 'masjidi-revamp',
    title: 'Masjidi Revamp',
    tags: ['React Native', 'Firebase', 'Claude API'],
    problem: 'Existing mosque management app had poor UX for prayer time notifications and event announcements.',
    aiUsage: 'Claude proposed UX improvements from user complaint logs and generated Firebase notification pipeline boilerplate.',
    outcome: 'Shipped to 3 pilot mosques, reducing support tickets by 40%.',
  },
  {
    id: 'marks-revamp',
    title: 'Marks Revamp',
    tags: ['React Native', 'Expo', 'Firebase'],
    problem: 'Goal-tracking app had slow startup and clunky habit-streak UI that hurt daily engagement.',
    aiUsage: 'Claude reviewed component trees for re-render issues and proposed a state architecture that halved the bundle size.',
    outcome: 'Cold-start time down 60%; animated progress rings shipped; daily active use up 2×.',
    github: 'https://github.com/MuhammedHMahmood/marks',
  },
  {
    id: 'cloudkraft',
    title: 'CloudKraft',
    tags: ['Terraform', 'AWS', 'CI/CD'],
    problem: 'Students needed a hands-on AWS sandbox that resets between sessions without manual teardown by instructors.',
    aiUsage: 'Claude authored Terraform modules from natural-language lab requirements and generated automated cleanup scripts.',
    outcome: 'Used in CMPE281 — 3 lab environments provisioned in under 4 minutes, zero manual teardown needed.',
  },
  {
    id: 'datatrust',
    title: 'DataTrust',
    tags: ['Claude API', 'Prompt Engineering', 'Node.js'],
    problem: 'Needed schema validation for AI-generated structured data without brittle regex validators.',
    aiUsage: 'Claude generates the data and validates against JSON Schema with a self-critique loop that catches type mismatches.',
    outcome: '94% schema validation accuracy on internal test suite; integrated into two prod pipelines as a pre-merge check.',
  },
];
